CREATE TABLE ARTICLES (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    CONTENT VARCHAR NOT NULL,
    TAGS VARCHAR NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL
);