CREATE TABLE USERS (
   ID BIGSERIAL PRIMARY KEY,
   USER_NAME VARCHAR NOT NULL UNIQUE,
   EMAIL VARCHAR NOT NULL,
   HASH VARCHAR NOT NULL,
   ROLE VARCHAR NOT NULL
);

CREATE TABLE ARTICLES (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    CONTENT VARCHAR NOT NULL,
    TAGS VARCHAR NOT NULL,
    USER_ID INT8 NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    DATE_CREATED TIMESTAMP NOT NULL
);

CREATE TABLE COMMENTS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID INT8 REFERENCES USERS (ID) ON DELETE CASCADE,
    ARTICLE_ID INT8 NOT NULL REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    BODY VARCHAR NOT NULL,
    ANONYM_NAME VARCHAR,
    DATE_CREATED TIMESTAMP NOT NULL,
    DATE_EDITED TIMESTAMP
);