CREATE TABLE ARTICLES (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    CONTENT VARCHAR NOT NULL,
    TAGS VARCHAR NOT NULL,
    USER_ID INT8 REFERENCES USERS (ID) ON DELETE CASCADE,
    DATE_CREATED TIMESTAMP NOT NULL
);