CREATE TABLE COMMENTS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID INT8 REFERENCES USERS (ID) ON DELETE CASCADE,
    ARTICLE_ID INT8 NOT NULL REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    BODY VARCHAR NOT NULL,
    ANONYM_NAME VARCHAR,
    DATE_CREATED TIMESTAMP NOT NULL,
    DATE_EDITED TIMESTAMP NOT NULL
);